### ISSUE TITLE
Getting Started Writing TM Content -- Where Do I Begin?

### ISSUE THREAD

**Issue by BendixSpring** [TMContent/Lib_Docs#6]
I tried to find out how to create content by going to the TM4TM site.

Instead of having something easy to follow, there was just all of this overwhelming content.  I didn't want to bother.  Too much work :-)

There needs to be a way for those of us who like to read a book from cover to cover serially to use the information on the site.  Otherwise, the end user has no real starting point.  

Here are some possible solutions:
1.  The quick start guide (Issue #1 https://github.com/TMContent/Lib_Docs/issues/1)
2.  Creating a Table of Contents with topics arranged in some logical order
3.  Numbering the articles so that they appear in some logical order

Even for the production TM system, having a Quick Start or Table of Contents would be valuable.

A document somewhat analogous to a "site map" would help if it could show some logical layout to the content where sequence is important -- maybe even have a "table of contents mode" that would allow a user to lock a "table of contents" with content.  It would allow the user to serially review the content.  Colored hyperlinks would indicate that the content has been read.  Multiple tables of content would be possible, depending on the user role, activity, platform, etc.

--Danny

**Comment by roman87** [comment]
This is done. Serge / Sandra has the document
